
%establish the time format for drift corrections

A.timeformat = get(gcbo,'tag');
if strcmp(A.timeformat,'integer_points') == 1 ;
    set(SCP.handles.driftpoints,'checked','on');
    set(SCP.handles.drifthhmm,'checked','off');
elseif strcmp(A.timeformat,'hhmm') == 1;
    set(SCP.handles.driftpoints,'checked','off');
    set(SCP.handles.drifthhmm,'checked','on');
end


if strcmp(A.timeformat,'integer_points') == 1

    TPS = struct('tps_fig',[],'handles',[]);

    TPS.tps_fig = figure('name','Drift Settings','color',[.5 .5 .5],'position',[980*sf(1) 800*sf(2) 200*sf(1) 100*sf(2)],'menubar','none','NumberTitle','off');

    TPS.handles = struct('h_header',[],'h_timepoints_edit',[]);

    TPS.handles.h_header =  uicontrol(TPS.tps_fig,'style','text','tag','TPS.handles.h_header',...
        'string','Total time points for drift correction:','position',[20*sf(1) 50*sf(2) 110*sf(1) 30*sf(2)],'HorizontalAlignment','left',...
        'backgroundcolor',[.5 .5 .5],'foregroundcolor',[1 1 1]);

    TPS.handles.h_timepoints_edit =  uicontrol(TPS.tps_fig,'style','edit','tag','TPS.handles.h_timepoints_edit',...
        'string',A.timepoints,'position',[140*sf(1) 50*sf(2) 40*sf(1) 20*sf(2)],'HorizontalAlignment','right',...
        'backgroundcolor',[1 1 1],'foregroundcolor',[0 0 0]);

    TPSET = ['clear A.timepoints;'...
        'A.timepoints = get(TPS.handles.h_timepoints_edit,''string'');'...
        'A.timepoints = str2num(A.timepoints);'...
        'if A.STD_num ~= 0;'...
        'for c = 1:A.STD_num;'...
        'if STD(c).timepoint > A.timepoints;'...
        'STD(c).timepoint = A.timepoints;'...
        'end;'...
        'end;'...
        'set(SCP.handles.h_currentSTD_driftpoints_popup,''string'',1:A.timepoints,''value'',STD(A.DC).timepoint,''Visible'',''on'');'...
        'set(SCP.handles.h_currentSTD_drifthh_edit,''Visible'',''off'');'...
        'set(SCP.handles.h_currentSTD_driftcolon,''Visible'',''off'');'...
        'set(SCP.handles.h_currentSTD_driftmm_edit,''Visible'',''off'');'...
        'end;'...
        'set(SCP.handles.h_currentSTD_driftpoints_popup,''string'',1:A.timepoints);'...
        'if A.UNK_num ~= 0;'...
        'for c = 1:A.UNK_num;'...
        'if UNK(A.KC).timepoint > A.timepoints;'...
        'UNK(A.KC).timepoint = A.timepoints;'...
        'end;'...
        'end;'...
        'end;'...
        'close(gcf);'];

    TPS.handles.h_ok_button =  uicontrol(TPS.tps_fig,'style','pushbutton','tag','TPS.handles.h_ok_button',...
        'string','OK','position',[75*sf(1) 10*sf(2) 50*sf(1) 20*sf(2)],'Callback',TPSET);

    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    % reduce the fontsize if a lower resolution monitor is being used
if sf(1) < 0.8
    child = get(gcf,'children');
    notmenu = find(strcmp(get(child,'type'),'uimenu') == 0);
    child = child(notmenu);
    set(child,'fontsize',7);
    clear child notmenu
end
    %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

elseif strcmp(A.timeformat,'hhmm')

    if A.STD_num > 0;
        set(SCP.handles.h_currentSTD_drifthh_edit,'Visible','on');
        set(SCP.handles.h_currentSTD_driftcolon,'Visible','on');
        set(SCP.handles.h_currentSTD_driftmm_edit,'Visible','on');
        set(SCP.handles.h_currentSTD_driftpoints_popup,'Visible','off');
    end
end