%FLICKER

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Sets up a box in which you can define the flicker noise, which is
% dependent on your instrument conditions
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

FLICKER = struct('flicker_fig',[],'handles',[]);

FLICKER.flicker_fig = figure('name','Flicker Noise Settings','color',[0 0 0],'position',[500*sf(1) 500*sf(2) 200*sf(1) 200*sf(2)],'menubar','none','NumberTitle','off','CloseRequestFcn','clear FLICKER,delete(gcf)');

FLICKER.handles = struct('h_header',[],'h_RSDflick_edit',[]);

FLICKER.handles.h_header1 =  uicontrol(FLICKER.flicker_fig,'style','text','tag','FLICKER.handles.h_header1',...
    'string','Set % Flicker Noise:','position',[20*sf(1) 150*sf(2) 160*sf(1) 20*sf(2)],'HorizontalAlignment','left',...
    'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);

FLICKER.handles.h_RSDflick_edit =  uicontrol(FLICKER.flicker_fig,'style','edit','tag','FLICKER.handles.h_RSDflick_edit',...
    'string',A.flickernoise,'position',[130*sf(1) 155*sf(2) 40*sf(1) 20*sf(2)],'HorizontalAlignment','right',...
    'backgroundcolor',[1 1 1],'foregroundcolor',[0 0 0]);

FLICKER.handles.h_header2 =  uicontrol(FLICKER.flicker_fig,'style','text','tag','FLICKER.handles.h_header2',...
    'string','Flicker noise was determined for what dwell time? (s)','position',[20*sf(1) 100*sf(2) 160*sf(1) 30*sf(2)],'HorizontalAlignment','left',...
    'backgroundcolor',[0 0 0],'foregroundcolor',[1 1 1]);

FLICKER.handles.h_flickDT_edit =  uicontrol(FLICKER.flicker_fig,'style','edit','tag','FLICKER.handles.h_flickDT_edit',...
    'string',A.flickDT,'position',[130*sf(1) 70*sf(2) 40*sf(1) 20*sf(2)],'HorizontalAlignment','right',...
    'backgroundcolor',[1 1 1],'foregroundcolor',[0 0 0]);

FLICKERSET = ['clear A.flickernoise;'...
    'flickernoise = get(FLICKER.handles.h_RSDflick_edit,''string'');'...
    'flickernoise = str2num(flickernoise);'...
    'if flickernoise < 0 || flickernoise > 100;'...
        'clear flickernoise;'...
        'msgbox(''Invalid Entry'');'...
        'return;'...
    'else;'...
        'A.flickernoise = flickernoise;'...
    'end;'...
    'flickDT = get(FLICKER.handles.h_flickDT_edit,''string'');'...
    'flickDT = str2num(flickDT);'...
    'if flickDT < 0;'...
        'clear flickDT;'...
        'msgbox(''Invalid Entry'');'...
        'return;'...
    'else;'...
        'A.flickDT = flickDT;'...
    'end;'...
    'delete(gcf);'...
    'clear FLICKER flickernoise flickDT;'];

FLICKER.handles.h_ok_button =  uicontrol(FLICKER.flicker_fig,'style','pushbutton','tag','FLICKER.handles.h_ok_button',...
    'string','OK','position',[75*sf(1) 10*sf(2) 50*sf(1) 20*sf(2)],'Callback',FLICKERSET);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% reduce the fontsize if a lower resolution monitor is being used
if sf(1) < 0.8
    child = get(gcf,'children');
    notmenu = find(strcmp(get(child,'type'),'uimenu') == 0);
    child = child(notmenu);
    set(child,'fontsize',7);
    clear child notmenu
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%