%HANDLEPURGE

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%This callback replaces all GUI items with a new set of handles.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

delete(gcf)
clear SCP.handles

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%SCREEN PARAMETERS

set(0,'units','pixels');
panelsize = get(0,'ScreenSize');
%screen dimensions in pixels
xy = [panelsize(3) panelsize(4)];

%ratio of width to height
xovery = xy(1)/xy(2);

if xovery > 1.33333333 %i.e. wider aspect ratio than my 1400x1050 screen...
    sf = [xy(2)/1050 xy(2)/1050]; %make the stretch factor relative to the height
else
    sf = [xy(1)/1400 xy(1)/1400]; %make the stretch factor relative to the width
end

%NOTE: the program was written using a 1400x1050 pixel screen, so if
%the monitor used is 1400x1050 as well, sf = [1 1]
%if the user's screen was 2000x1000, xovery = 2, and sf = [0.9524 0.9524];

clear xy xovery panelsize
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

SCP.handles = struct('h_fig',[],'file',[],'help',[],'wkspopen',[],'wkspsave',[],'exitsave',[],'h_frame1',[],'h_frame2',[],'h_load_srm_button',[],'h_add_srm_button',[],'h_plot_srm_button',[],...
    'h_currentSRM_header',[],'h_currentSRM_popup',[],'h_load_std_button',[],'h_currentSTD_header',[],...
    'h_currentSTD_header2',[],'h_currentSTD_filename',[],'h_currentSTD_SRM',[],'h_currentSTD_bg',[],...
    'h_currentSTD_bgfrom',[],'h_currentSTD_bgto',[],'h_currentSTD_bgtotal',[],'h_currentSTD_sig',[],...
    'h_currentSTD_sigfrom',[],'h_currentSTD_sigto',[],'h_currentSTD_sigtotal',[],'h_currentSTD_filename_out',[],...
    'h_currentSTD_SRM_out',[],'h_currentSTD_bgfrom_out',[],'h_currentSTD_bgto_out',[],'h_currentSTD_bgtotal_out',[],...
    'h_currentSTD_sigfrom_out',[],'h_currentSTD_sigto_out',[],'h_currentSTD_sigtotal_out',[],'h_currentSTD_popup',[]);

SCP.handles.h_fig =         figure('name','SILLS Project: Untitled','tag','SILLS Control Panel','UserData',0,...
    'Color',[1 1 1],'NumberTitle','off','position',[1040*sf(1) 230*sf(2) 430*sf(1) 770*sf(2)],'menubar','none');
SCP.handles.file =          uimenu('Label','File');
SCP.handles.settings =      uimenu('Label','Settings');
set(SCP.handles.h_fig,'DockControls','off'); %Changed in 1.0.2
SCP.handles.automate =      uimenu('Label','Automate'); %Added in 1.0.6
SCP.handles.help =          uimenu('Label','Help'); %Added in 1.0.5

SCP.handles.wkspnew =  uimenu(SCP.handles.file,'Label','New Project','Callback',SILLSNEW);
SCP.handles.wkspopen = uimenu(SCP.handles.file,'Label','Open Project','Callback','SILLSOPEN');
SCP.handles.wkspsave = uimenu(SCP.handles.file,'Label','Save Project','Callback',SILLSSAVE);
SCP.handles.exitsave = uimenu(SCP.handles.file,'Label','Exit','Callback',SILLSEXIT);
set(SCP.handles.h_fig,'CloseRequestFcn',SILLSEXIT);


SCP.handles.input =    uimenu(SCP.handles.settings,'Label','Input Format');
SCP.handles.cps =      uimenu(SCP.handles.input,'Label','Counts per second','tag','cps','checked','on','Callback',SILLSINPUT);
SCP.handles.counts =   uimenu(SCP.handles.input,'Label','Absolute counts','tag','cts','checked','off','Callback',SILLSINPUT);

SCP.handles.time_format =   uimenu(SCP.handles.settings,'Label','Time Format');
SCP.handles.drifthhmm =     uimenu(SCP.handles.time_format,'Label','hh:mm','tag','hhmm','checked','on','Callback','DRIFTSETTINGS');
SCP.handles.driftpoints =   uimenu(SCP.handles.time_format,'Label','Integer time points','tag','integer_points','Callback','DRIFTSETTINGS');

SCP.handles.autotime =      uimenu(SCP.handles.automate,'Label','Retrieve Times from File Info','Callback','AUTOTIME'); %Added in 1.0.5
SCP.handles.autoint =       uimenu(SCP.handles.automate,'Label','Set Integration Intervals Automatically','Callback','AUTOINT'); %Added in 1.0.6

SCP.handles.SRM =           uimenu(SCP.handles.settings,'Label','Standard Reference Materials');
SCP.handles.SRMload =       uimenu(SCP.handles.SRM,'Label','Load SRM from file','Callback','USERSRM_LOAD');
SCP.handles.SRMdefine =     uimenu(SCP.handles.SRM,'Label','Define new SRM','Callback','ADD_SRM');

SCP.handles.dwelltimes =    uimenu(SCP.handles.settings,'Label','Set Dwell Times','Callback','DWELLTIMES');

SCP.handles.flicker =       uimenu(SCP.handles.settings,'Label','Set Flicker Noise','Callback','FLICKER_SET');

 %Added in 1.0.5
SCP.handles.manual = uimenu(SCP.handles.help,'Label','SILLS Manual','Callback','open([pwd ''/Extras/SILLS Manual.pdf''])');
SCP.handles.about =  uimenu(SCP.handles.help,'Label','About SILLS',...
    'Callback','msgbox(textread([pwd ''/Extras/about.txt''],''%s'',''delimiter'',''\n''),''About SILLS'')');

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

SCP.handles.h_frame2 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame2',...
    'position',[10*sf(1) 340*sf(2) 170*sf(1) 220*sf(2)],...
    'BackgroundColor',[0.5137 0.6 0.6941],'ForegroundColor',[0.5137 0.6 0.6941]);

SCP.handles.h_frame3 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame3',...
    'position',[10*sf(1) 10*sf(2) 170*sf(1) 320*sf(2)],...
    'Backgroundcolor',[0.8039 0.7529 0.6902],'Foregroundcolor',[0.8039 0.7529 0.6902]);

SCP.handles.h_frame4 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame',...
    'position',[185*sf(1) 340*sf(2) 235*sf(1) 220*sf(2)],...
    'Backgroundcolor',[0 0 0],'Foregroundcolor',[0.5137 0.6 0.6941]);

SCP.handles.h_frame5 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame5',...
    'position',[185*sf(1) 10*sf(2) 235*sf(1) 320*sf(2)],...
    'Backgroundcolor',[ 0 0 0],'Foregroundcolor',[0.8039 0.7529 0.6902]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 5.4 set up GUI objects for the standard

SCP.handles.h_load_std_button =     uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_load_std_button',...
    'Callback','STDFILE_LOAD',...
    'string','Load New Standard','Fontweight','bold',...
    'position',[20*sf(1) 520*sf(2) 150*sf(1) 30*sf(2)],...
    'backgroundcolor',[0.5137 0.6 0.6941]);

SCP.handles.h_currentSTD_header =       uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_header',...
    'string','Current Standards:','ForegroundColor',[1 1 1],'BackgroundColor',[0.5137 0.6 0.6941],...
    'HorizontalAlignment','left','position',[20*sf(1) 490*sf(2) 150*sf(1) 20*sf(2)]);

SCP.handles.h_currentSTD_popup =        uicontrol(SCP.handles.h_fig,'style','popupmenu','tag','SCP.handles.h_currentSTD_popup',...
    'string','< load a standard >','Callback','SILLSFIG_UPDATE','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[20*sf(1) 475*sf(2) 150*sf(1) 20*sf(2)]);
% NB: as new standards are added, 'A.STDPOPUPLIST' is expanded and the popup is updated

SCP.handles.h_std_plot_button =         uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_std_plot_button',...
    'string','Plot Selected Standard','position',[20*sf(1) 430*sf(2) 150*sf(1) 30*sf(2)],...
    'backgroundcolor',[0.5137 0.6 0.6941],'Callback','STDPLOT');

SCP.handles.h_std_delete_button =       uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_std_delete_button',...
    'string','Delete Selected Standard','Callback','STDDELETE','position',[20*sf(1) 390*sf(2) 150*sf(1) 30*sf(2)],'backgroundcolor',[0.5137 0.6 0.6941]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 5.5 Set up the text display elements for the current (i.e. selected) standard

SCP.handles.h_currentSTD_header2 =      uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_header2',...
    'string','Data for Selected Standard','Fontweight','bold','ForegroundColor',[0.5137 0.6 0.6941],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 525*sf(2) 180*sf(1) 20*sf(2)]);

SCP.handles.h_currentSTD_filename =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_filename',...
    'string','filename:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[200*sf(1) 505*sf(2) 70*sf(1) 20*sf(2)]);

SCP.handles.h_currentSTD_SRM =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_SRM',...
    'string','Assign SRM:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[200*sf(1) 480*sf(2) 70*sf(1) 20*sf(2)]);

SCP.handles.h_currentSTD_driftset_header =      uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_driftset_header',...
    'string','Assign time:','position',[200*sf(1) 455*sf(2) 70*sf(1) 20*sf(2)],'HorizontalAlignment','right',...
    'backgroundcolor',[0 0 0],'foregroundcolor',[.8 .8 .8],'Callback','STDPLOT');

SCP.handles.h_currentSTD_bg =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bg',...
    'string','BKGND','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 430*sf(2) 80*sf(1) 20*sf(2)]);
SCP.handles.h_currentSTD_bgfrom =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgfrom',...
    'string','from:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 420*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentSTD_bgto =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgto',...
    'string','to:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 405*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentSTD_bgtotal =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgtotal',...
    'string','total:','HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 390*sf(2) 50*sf(1) 15*sf(2)]);

SCP.handles.h_currentSTD_sig =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sig',...
    'string','SIGNAL','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[340*sf(1) 430*sf(2) 60*sf(1) 20*sf(2)]);

SCP.handles.h_currentSTD_filename_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_filename_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','left','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[280*sf(1) 505*sf(2) 120*sf(1) 20*sf(2)]);

SCP.handles.h_currentSTD_SRM_out = uicontrol(SCP.handles.h_fig,'style','popup','tag','SCP.handles.h_currentSTD_SRM_out','string',A.SRMPOPUPLIST,'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','left','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],'Callback','SILLSFIG_UPDATE',...
    'position',[280*sf(1) 485*sf(2) 120*sf(1) 20*sf(2)],'visible','off');

SCP.handles.h_currentSTD_drifthh_edit = uicontrol(SCP.handles.h_fig,'style','edit','tag','SCP.handles.h_currentSTD_drifthh_edit',...
    'HorizontalAlignment','center','ForegroundColor',[0 0 0],'BackgroundColor',[1 1 1],'Callback','TIMESET',...
    'position',[280*sf(1) 460*sf(2) 25*sf(1) 20*sf(2)],'Visible','off');
SCP.handles.h_currentSTD_driftcolon = uicontrol(SCP.handles.h_fig,'style','text','string',':','tag','SCP.handles.h_currentSTD_driftcolon',...
    'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[307*sf(1) 455*sf(2) 5*sf(1) 20*sf(2)],'Visible','off');
SCP.handles.h_currentSTD_driftmm_edit = uicontrol(SCP.handles.h_fig,'style','edit','tag','SCP.handles.h_currentSTD_driftmm_edit',...
    'HorizontalAlignment','center','ForegroundColor',[0 0 0],'BackgroundColor',[1 1 1],'Callback','TIMESET',...
    'position',[315*sf(1) 460*sf(2) 25*sf(1) 20*sf(2)],'Visible','off');

TIMEPT_STDASSIGN = 'STD(A.DC).timepoint = get(gco,''value'');';

SCP.handles.h_currentSTD_driftpoints_popup = uicontrol(SCP.handles.h_fig,'style','popup','tag','SCP.handles.h_currentSTD_driftpoints_popup',...
    'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],'string',1:A.timepoints,'HorizontalAlignment','right','Callback',TIMEPT_STDASSIGN,...
    'position',[280*sf(1) 460*sf(2) 50*sf(1) 20*sf(2)],'Visible','off');

SCP.handles.h_currentSTD_bgfrom_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgfrom_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 420*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentSTD_bgto_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgto_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 405*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentSTD_bgtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgtotal_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 390*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentSTD_sigfrom_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sigfrom_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[340*sf(1) 420*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentSTD_sigto_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sigto_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[340*sf(1) 405*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentSTD_sigtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sigtotal_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[340*sf(1) 390*sf(2) 40*sf(1) 15*sf(2)]);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 5.6 Set up the Unknown GUI elements

SCP.handles.h_currentUNK_header =       uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_header',...
    'string','Current Unknowns:','ForegroundColor',[1 1 1],'BackgroundColor',[0.8039 0.7529 0.6902],...
    'HorizontalAlignment','left','position',[20*sf(1) 260*sf(2) 150*sf(1) 20*sf(2)]);

SCP.handles.h_load_unk_button =     uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_load_unk_button',...
    'Callback','UNKFILE_LOAD',...
    'string','Load New Unknown','Fontweight','bold',...
    'position',[20*sf(1) 290*sf(2) 150*sf(1) 30*sf(2)],...
    'backgroundcolor',[0.8039 0.7529 0.6902]);

SCP.handles.h_currentUNK_popup =        uicontrol(SCP.handles.h_fig,'style','popupmenu','tag','SCP.handles.h_currentUNK_popup',...
    'string','< load an unknown >','Callback','SILLSFIG_UPDATE','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[20*sf(1) 245*sf(2) 150*sf(1) 20*sf(2)]);
% NB: as new unknowns are added, 'unkpopuplist' is expanded

SCP.handles.h_unk_plot_button =         uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_unk_plot_button',...
    'string','Plot Selected Unknown','position',[20*sf(1) 200*sf(2) 150*sf(1) 30*sf(2)],...
    'backgroundcolor',[0.8039 0.7529 0.6902],'Callback','UNKPLOT');

SCP.handles.h_unk_copy_button =       uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_unk_copy_button',...
    'string','Copy Selected Unknown','Callback','UNKCOPY','position',[20*sf(1) 160*sf(2) 150*sf(1) 30*sf(2)],'backgroundcolor',[0.8039 0.7529 0.6902]);

SCP.handles.h_unk_delete_button =       uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_unk_delete_button',...
    'string','Delete Selected Unknown','Callback','UNKDELETE','position',[20*sf(1) 120*sf(2) 150*sf(1) 30*sf(2)],'backgroundcolor',[0.8039 0.7529 0.6902]);

SCP.handles.h_CALC_manager = uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_CALC_manager',...
    'string','CALCULATION SETTINGS','Callback','CALC_MANAGER','BackgroundColor',[0.8039 0.7529 0.6902],'position',[20*sf(1) 50*sf(2) 150*sf(1) 60*sf(2)]);

% 5.7 Set up the text display elements for the current (i.e. selected) standard

SCP.handles.h_currentUNK_header2 =      uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_header2',...
    'string','Data for Selected Unknown','Fontweight','bold','ForegroundColor',[0.8039 0.7529 0.6902],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 300*sf(2) 180*sf(1) 20*sf(2)]);

SCP.handles.h_currentUNK_filename =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_filename',...
    'string','filename:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[200*sf(1) 280*sf(2) 70*sf(1) 20*sf(2)]);

%     SCP.handles.h_currentUNK_driftset_header =      uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_driftset_header',...
%         'string','Assign time:','position',[370*sf(1) 255*sf(2) 70*sf(1) 20*sf(2)],'HorizontalAlignment','right',...
%         'backgroundcolor',[0 0 0],'foregroundcolor',[.8 .8 .8]);

SCP.handles.h_currentUNK_bg =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bg',...
    'string','BKGND','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 210*sf(2) 80*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_bgfrom =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgfrom',...
    'string','from:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 180*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_bgto =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgto',...
    'string','to:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 165*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_subtotal =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_total',...
    'string','subtotal:','HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 150*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_total =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_total',...
    'string','total:','HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 135*sf(2) 50*sf(1) 15*sf(2)]);

SCP.handles.h_currentUNK_mat =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat',...
    'string','MATRIX','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[340*sf(1) 210*sf(2) 60*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_mat1 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat1',...
    'string','Comp. 1','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[315*sf(1) 195*sf(2) 50*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_mat2 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat1',...
    'string','Comp. 2','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[365*sf(1) 195*sf(2) 50*sf(1) 20*sf(2)]);

%%%%%%%%%%%%%%%%%%%%%%
SCP.handles.h_currentUNK_filename_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_filename_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','left','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[280*sf(1) 280*sf(2) 120*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_bgfrom_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgfrom_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 180*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_bgto_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgto_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 165*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_bgtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgtotal_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[260*sf(1) 135*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_mat1from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_matfrom_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
    'position',[315*sf(1) 180*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_mat1to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_matto_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
    'position',[315*sf(1) 165*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_mat2from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat2from_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
    'position',[365*sf(1) 180*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_mat2to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat2to_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
    'position',[365*sf(1) 165*sf(2) 40*sf(1) 15*sf(2)]);

SCP.handles.h_currentUNK_mat1total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat1total_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[315*sf(1) 150*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_mat2total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat2total_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[365*sf(1) 150*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_mattotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mattotal_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[340*sf(1) 135*sf(2) 40*sf(1) 15*sf(2)]);

SCP.handles.h_currentUNK_sig =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_sig',...
    'string','SIGNAL','HorizontalAlignment','center','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[250*sf(1) 100*sf(2) 150*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_comp1 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1',...
    'string','Comp.1','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[250*sf(1) 85*sf(2) 50*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_comp2 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2',...
    'string','Comp.2','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[300*sf(1) 85*sf(2) 50*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_comp3 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3',...
    'string','Comp.3','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[350*sf(1) 85*sf(2) 50*sf(1) 20*sf(2)]);
SCP.handles.h_currentUNK_comp1from =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1from',...
    'string','from:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 70*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp1to =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1to',...
    'string','to:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 55*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp1total =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1total',...
    'string','subtotal:','HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 40*sf(2) 50*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_sigtotal =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_sigtotal',...
    'string','total:','HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[190*sf(1) 25*sf(2) 50*sf(1) 15*sf(2)]);


SCP.handles.h_currentUNK_comp1from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1from_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[250*sf(1) 70*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp1to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1to_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[250*sf(1) 55*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp1total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1total_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[250*sf(1) 40*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp2from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2from_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[300*sf(1) 70*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp2to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2to_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[300*sf(1) 55*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp2total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2total_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[300*sf(1) 40*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp3from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3from_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[350*sf(1) 70*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp3to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3to_out','string',[],'ForegroundColor',[1 1 1],...
    'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
    'position',[350*sf(1) 55*sf(2) 40*sf(1) 15*sf(2)]);
SCP.handles.h_currentUNK_comp3total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3total_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'position',[350*sf(1) 40*sf(2) 40*sf(1) 15*sf(2)]);

SCP.handles.h_currentUNK_sigtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_sigtotal_out',...
    'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
    'position',[300*sf(1) 25*sf(2) 40*sf(1) 15*sf(2)]);

%%%%%% Display the logo %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

logo = imread([pwd '/Extras/SILLSlogo.jpg']); %Changed in 1.0.4
image(logo);
set(gca,'visible','off','units','pixels','position',[50*sf(1) 570*sf(2) 320*sf(1) 184*sf(2)]);
clear logo

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%% Declare all windows closed %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

if ~isempty(A.STD_num) && A.STD_num > 0
    for c = 1:A.STD_num
        STD(c).figure_state = 'shut';
    end
end

if ~isempty(A.UNK_num) && A.UNK_num > 0
    for c = 1:A.UNK_num
        UNK(c).figure_state = 'shut';
    end
end

A.CALC_MANAGER_open = 0;
A.SIGQUANT_open = 0;
A.SIGSALT_open = 0;
A.CALIBPLOT_open = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

