%SAVEFIGAS.m
%This script is called by the 'Save As' command in the menu of the standard
%and unknown plots.
%Added in 1.0.2

extensions = {'*.fig','MATLAB Figure (*.fig)';...
    '*.ai','Adobe Illustrator file (*.ai)';...
    '*.bmp','Bitmap file (*.bmp)';...
    '*.emf','Enhanced metafile (*.emf)';...
    '*.eps','EPS file (*.eps)';...
    '*.jpg','JPEG Image (*.jpg)';...
    '*.pbm','Portable Bitmap file (*.pbm)';...
    '*.pcx','Paintbrush 24-bit file (*.pcx)';...
    '*.pgm','Portable Graymap file (*.pgm)';...
    '*.png','Portable Networks Graphics file (*.png)';...
    '*.ppm','Portable Pixmap file (*.ppm)';...
    '*.tif','TIFF image (*.tif)'};

%Default name is the name of the data file, points replaced by underscore
%preventing confusion with extensions
defaultname = get(gcf,'Tag');
defaultname(strfind(defaultname,'.')) = '_';

[figurefilename,figurepath] = uiputfile(extensions,'Save image as',defaultname);
if figurefilename ~= 0
    saveas(gcf,[figurepath figurefilename]);
    clear extensions defaultname figurefilename figurepath
else
    clear extensions defaultname figurefilename figurepath
    return
end