%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% SILLS %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%  Signal Integration for the Leeds Laser System  %%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%                                                                     %%
%%  Software written by Murray Allan 2004-2007. All SILLS-related      %%
%%  scripts are joint intellectual property of the University of Leeds %%
%%  and ETH and intended for academic use only.                        %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%close all open MATLAB windows (up to 50)
for c = 1:50
    delete(gcf)
end

%eliminate all variables from Workspace
clear all 

warning off

%Check if Extras and SRM Files folders are present
%Added in 1.0.4
if ~isdir('Extras') || ~isdir('SRM Files')
    msgbox('"Extras" or "SRM Files" folder not found. Make sure they are in the same directory as the SILLS program',...
        'SILLS Error Message','error');
    return
end

%%%%%%%%%% Section 1 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This section determines the dimensions of the monitor being used
% and scales the figure accordingly using the variable 'sf' or
% 'stretch factor'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

set(0,'units','pixels');
panelsize = get(0,'ScreenSize');
%screen dimensions in pixels
xy = [panelsize(3) panelsize(4)];

%ratio of width to height
xovery = xy(1)/xy(2);

if xovery > 1.33333333 %i.e. wider aspect ratio than my 1400x1050 screen...
    sf = [xy(2)/1050 xy(2)/1050]; %make the stretch factor relative to the height
else
    sf = [xy(1)/1400 xy(1)/1400]; %make the stretch factor relative to the width
end

%NOTE: the program was written using a 1400x1050 pixel screen, so if
%the monitor used is 1400x1050 as well, sf = [1 1]
%if the user's screen was 2000x1000, xovery = 2, and sf = [0.9524 0.9524];

clear xy xovery panelsize


%%%%%%%%%% Section 2: set up the structure arrays %%%%%%%%%%%%%%%%%%%%%%%%%
%Set up SMAN structure array (contains elements of the calculation manager figure)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

SMAN = struct('h_SMAN',[],'headers',[],'handles',[],'figure_state','shut');

%Set up STD structure array (contains all information about the calibration standards)
STD = struct('data',[],'textdata',[],'colheaders',[],'fileinfo',[],'num_elements',[],...
            'SRM',[],'bgwindow',[],'sigwindow',[],'order_opened',[],...
            'figure_state',[],'timepoint',[],'XLim_orig',[],'YLim_orig',[],'YLim_orig_element',[],'handles',[],...
            'incrmt',[],'lines',[],'hh',[],'mm',[]);

%Set up UNK structure array (contains all information about the analytes
UNK = struct('data',[],'textdata',[],'colheaders',[],'fileinfo',[],'num_elements',[],...
            'internal_standard',[],'bgwindow',[],'mat1window',[],'mat2window',[],'mattotal',[],...
            'comp1window',[],'comp2window',[],'comp3window',[],'sigtotal',[],...
            'XLim_orig',[],'YLim_orig',[],'YLim_orig_element',[],...
            'order_opened',[],'figure_state',[],'timepoint',[],'hh',[],'mm',[],'Info',[],...
            'MAT_corrtype',[],'MATcorrfile',[],'MATcorrfile_index',[],'MATQIS',[],'MATQISiso',[],'MATQISox',[],'MATQIS_conc',[],'MATQIS_concwt',[],'MATunit',1,...
            'MATQIS_conc_error',[],'MAT_oxide_total',[],'MAT_oxide_total_error',[],'MAT_Fe_ratio',[],...
            'SIG_quanttype',[],...
            'SIGQIS1',[],'SIGQIS1iso',[],'SIGQIS1ox',[],...
            'SIGQIS1_conc',[],'SIGQIS1_concwt',[],...
            'SIGQIS1_conc_error',[],'SIG1unit',1,...            
            'SIGQIS2',[],'SIGQIS2iso',[],'SIGQIS2ox',[],...
            'SIGQIS2_conc',[],'SIGQIS2_concwt',[],...
            'SIGQIS2_conc_error',[],'SIG2unit',1,...
            'SIGsalinity',[],'SIGsalinity_error',[],'SALT',[],'SALT_mass_balance_factor',0.5,... %Mass balance factor changed in 1.0.6
            'SIG_oxide_total',[],'SIG_oxide_total_error',[],'SIG_Fe_ratio',[],...
            'SIG_constraint1',[],'SIG_constraint2',[],'SIG_tracer',[],'SIG_traceriso',[]);

% Set up the A structure array (contains all universal variables)
A = struct( 'sillsdir',[],'sillsfile',[],...
            'sillspath',[],'SRM_files',[],'SRM_num',[],...
            'SRM_filenames',[],'userSRMfile',[],'userSRMpathname',[],...
            'SRMcheck',[],'USERSRMFILE',[],'MC',[],...
            'STD_num',[],'d',[],'D',[],'DC',[],...
            'UNK_num',[],'k',[],'K',[],'KC',[],...
            'input_type','cps',...
            'timeformat','hhmm','timepoints',1,'flickernoise',0,...
            'flickDT',0.010,'ISOTOPE_list',[],'ISOTOPE_num',[],...
            'CALC_MANAGER_open',0,'SIGQUANT_open',0,'SIGSALT_open',0,...
            'Oxide_test',0,'Oxides',[],'DT_VALUES',[],...
            'UNK_with_matrix',[],'UNK_with_matrix_index',[],...
            'UNK_with_matrix_num',0,'REFIS','','REFIS_list_index',1,...
            'REPORTIS','','REPORTIS_list_index',1,'STD_TIMES',[],...
            'UNK_TIMES',[],'DRIFT_regression',[],'CALIB',[],...
            'report_settings_oxide','off','report_settings_population','off',...
            'CALIBPLOT_open',0,'CAL_xisotope',1,'CAL_yisotope',1,...
            'dummy',0.1,'LODff',3,'cpsonly',0,'LODmethod','Pettke'); %changed in 1.0.2 (Added dummy and LODff value) and 1.0.3; Added LODmethod in 1.3.2
        
A.STDPOPUPLIST = {}; %Added in 1.1.0
A.UNKPOPUPLIST = {}; %Added in 1.1.0
A.ratios.num = 0; %Added in 1.0.4
A.ratios.index = []; %Added in 1.0.4
A.ratios.show = []; %Added in 1.0.4
A.ratios.names = {}; %Added in 1.0.4

%define a matrix containing the common rock-forming oxides

A.Oxides = {'Si' 'SiO2';
           'Ti' 'TiO2';
           'Al' 'Al2O3';
           'Fe' 'Fe2O3';
           'Fe' 'FeO';
           'Mn' 'MnO';
           'Mg' 'MgO';
           'Ca' 'CaO';
           'Na' 'Na2O';
           'K' 'K2O';
           'P' 'P2O5'};
        
A.Oxides_mol_wts = [28.09 60.09 1;
           47.87 79.90 1;
           26.98 101.96 2;
           55.85 159.69 2;
           55.85 71.85 1;
           54.94 70.94 1;
           24.30 40.31 1;
           40.08 56.08 1;
           22.99 61.98 2;
           39.10 94.20 2;
           30.97 141.95 2];
      
%define a matrix containing chlorides

A.Chlorides = {'Li' 'LiCl';
    'Be' 'BeCl2';
    'B' 'BCl3';
    'Na' 'NaCl';
    'Mg' 'MgCl2';
    'Al' 'AlCl3';
    'Si' 'SiCl4';
    'P' 'PCl5';
    'K' 'KCl';
    'Ca' 'CaCl2';
    'Sc' 'ScCl3';
    'Ti' 'TiCl4';
    'V' 'VCl4';
    'Cr' 'CrCl3';
    'Mn' 'MnCl2';
    'Fe' 'FeCl2';
    'Co' 'CoCl2';
    'Ni' 'NiCl2';
    'Cu' 'CuCl';
    'Zn' 'ZnCl2';
    'Ga' 'GaCl3';
    'Ge' 'GeCl2';
    'As' 'AsCl3';
    'Rb' 'RbCl';
    'Sr' 'SrCl2';
    'Y' 'YCl3';
    'Zr' 'ZrCl4';
    'Nb' 'NbCl5';
    'Mo' 'MoCl6';
    'Tc' 'TcCl2';
    'Ru' 'RuCl3';
    'Rh' 'RhCl3';
    'Pd' 'PdCl2';
    'Ag' 'AgCl';
    'Cd' 'CdCl2';
    'In' 'InCl3';
    'Sn' 'SnCl2';
    'Sb' 'SbCl3';
    'Cs' 'CsCl';
    'Ba' 'BaCl2';
    'La' 'LaCl3';
    'Ce' 'CeCl3';
    'Pr' 'PrCl3';
    'Nd' 'NdCl3';
    'Pm' 'PmCl3';
    'Sm' 'SmCl3';
    'Eu' 'EuCl3';
    'Gd' 'GdCl2';
    'Tb' 'TbCl3';
    'Dy' 'DyCl3';
    'Ho' 'HoCl3';
    'Er' 'ErCl3';
    'Tm' 'TmCl3';
    'Yb' 'YbCl3';
    'Lu' 'LuCl3';
    'Hf' 'HfCl4';
    'Ta' 'TaCl5';
    'W' 'WCl6';
    'Re' 'ReCl4';
    'Os' 'OsCl4';
    'Ir' 'IrCl4';
    'Pt' 'PtCl4';
    'Au' 'AuCl';
    'Hg' 'HgCl';
    'Tl' 'TlCl';
    'Pb' 'PbCl2';
    'Bi' 'BiCl3';
    'Th' 'ThCl4';
    'U' 'UCl4'};
    
A.Chlorides_mol_wts = [6.94 42.39 1;
    9.01 79.91 2;
    10.81 117.16 3;
    22.99 58.44 1;
    24.3 95.2 2;
    26.98 133.33 3;
    28.09 169.89 4;
    30.97 208.22 5;
    39.1 74.55 1;
    40.08 110.98 2;
    44.96 151.31 3;
    47.87 189.67 4;
    50.94 192.74 4;
    52 158.35 3;
    54.94 125.84 2;
    55.85 126.75 2;
    58.93 129.83 2;
    58.69 129.59 2;
    63.55 99 1;
    65.39 136.29 2;
    69.72 176.07 3;
    72.61 143.51 2;
    74.92 181.27 3;
    85.47 120.92 1;
    87.62 158.52 2;
    88.91 195.26 3;
    91.22 233.02 4;
    92.91 270.16 5;
    95.94 308.64 6;
    98.91 169.81 2;
    101.1 207.45 3;
    102.9 209.25 3;
    106.4 177.3 2;
    107.9 143.35 1;
    112.4 183.3 2;
    114.8 221.15 3;
    118.7 189.6 2;
    121.8 228.15 3;
    132.9 168.35 1;
    137.3 208.2 2;
    138.9 245.25 3;
    140.1 246.45 3;
    140.9 247.25 3;
    144.2 250.55 3;
    146.9 253.25 3;
    150.4 256.75 3;
    152.0 258.35 3;
    157.2 228.1 2;
    158.9 265.25 3;
    162.5 268.85 3;
    164.9 271.25 3;
    167.3 273.65 3;
    168.9 275.25 3;
    173.0 279.35 3;
    175.0 281.35 3;
    178.5 320.3 4;
    180.9 358.15 5;
    183.8 396.5 6;
    186.2 328 4;
    190.2 332 4;
    192.2 334 4;
    195.1 336.9 4;
    197 232.45 1;
    200.6 236.05 1;
    204.4 239.85 1;
    207.2 278.1 2;
    209 315.35 3;
    232 373.8 4;
    238 379.8 4];
    
A.Chlorides_num = size(A.Chlorides);
A.Chlorides_num = A.Chlorides_num(1);
    
           
A.STD_num = 0;
A.d = 0;
A.D = 0;
A.DC = 0;
% Note: A.d is the number of times a standard figure has been opened, irrespective of deletions
%       A.D is the number of open standard figures

A.UNK_num = 0;
A.k = 0;
A.K = 0;
A.KC = 0;
% Note: A.k is the number of times a standard figure has been opened, irrespective of deletions
%       A.K is the number of open standard figures


%%%%%%%%%% Section 3: read in 3 SRM data: NIS_612, NIST_610, STDGL_2b2 data %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% First setup SRM structure array
SRM = struct('data',[],'textdata',[],'rowheaders',[],'fileinfo',[],'name',[]);

A.SRM_num = 1;  % number of SRM's loaded into the SILLS session
A.MC = 1;       % the current SRM

B = importdata([pwd '/SRM Files/NIST_612.xls']); %Changed in 1.0.4
SRM.data = B.data;
SRM.textdata = B.textdata;
SRM.rowheaders = B.rowheaders;
SRM.fileinfo = dir(fullfile(pwd,'SRM Files/NIST_612.xls')); %Changed in 1.0.4
SRM.name = SRM.fileinfo.name;
clear B;
A.SRMPOPUPLIST = {SRM.name};

%added in 1.2 by MG

A.SRM_num = A.SRM_num + 1; % a new SRM added
                       
        B = importdata([pwd '/SRM Files/NIST_610.xls']); %Changed in 1.0.4
        SRM(A.SRM_num,1).data = B.data;
        SRM(A.SRM_num,1).textdata = B.textdata;
        SRM(A.SRM_num,1).rowheaders = B.rowheaders;
        SRM(A.SRM_num,1).fileinfo = dir(fullfile(pwd,'SRM Files/NIST_610.xls')); %Changed in 1.0.4
        SRM(A.SRM_num,1).name = SRM(A.SRM_num,1).fileinfo.name;
        clear B
A.SRMPOPUPLIST = vertcat(A.SRMPOPUPLIST,SRM(A.SRM_num,1).name);
   
        
A.SRM_num = A.SRM_num + 1; % a new SRM added
                        
        B = importdata([pwd '/SRM Files/STDGL-2b2.xls']); %Changed in 1.0.4
        SRM(A.SRM_num,1).data = B.data;
        SRM(A.SRM_num,1).textdata = B.textdata;
        SRM(A.SRM_num,1).rowheaders = B.rowheaders;
        SRM(A.SRM_num,1).fileinfo = dir(fullfile(pwd,'SRM Files/STDGL-2b2.xls')); %Changed in 1.0.4
        SRM(A.SRM_num,1).name = SRM(A.SRM_num,1).fileinfo.name;
        clear B
A.SRMPOPUPLIST = vertcat(A.SRMPOPUPLIST,SRM(A.SRM_num,1).name);
% stop added by MG
 
%A.SRMPOPUPLIST = vertcat(A.SRMPOPUPLIST,SRM(A.SRM_num,1).name); removed by
%MG

%%%%%%%%%% Section 4: Create the SILLS Control Panel %%%%%%%%%%%%%%%%%%%%%%
%
% The following code creates all graphical-user-interface (GUI) objects
%
% NB: all object handles have been given the prefix 'h_....', and tags have
% been given the same name.
%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% 4.1 set up the SCP.handles structure array

    SCP.handles = struct('h_fig',[],'file',[],'help',[],'wkspopen',[],'wkspsave',[],'exitsave',[],'h_frame1',[],'h_frame2',[],'h_load_srm_button',[],'h_add_srm_button',[],'h_plot_srm_button',[],...
        'h_currentSRM_header',[],'h_currentSRM_popup',[],'h_load_std_button',[],'h_currentSTD_header',[],...
        'h_currentSTD_header2',[],'h_currentSTD_filename',[],'h_currentSTD_SRM',[],'h_currentSTD_bg',[],...
        'h_currentSTD_bgfrom',[],'h_currentSTD_bgto',[],'h_currentSTD_bgtotal',[],'h_currentSTD_sig',[],...
        'h_currentSTD_sigfrom',[],'h_currentSTD_sigto',[],'h_currentSTD_sigtotal',[],'h_currentSTD_filename_out',[],... 
        'h_currentSTD_SRM_out',[],'h_currentSTD_bgfrom_out',[],'h_currentSTD_bgto_out',[],'h_currentSTD_bgtotal_out',[],...
        'h_currentSTD_sigfrom_out',[],'h_currentSTD_sigto_out',[],'h_currentSTD_sigtotal_out',[],'h_currentSTD_popup',[]);

    SCP.handles.h_fig =         figure('name','SILLS Project: Untitled','tag','SILLS Control Panel','UserData',0,...
        'Color',[1 1 1],'NumberTitle','off','position',[1040*sf(1) 230*sf(2) 430*sf(1) 770*sf(2)],'menubar','none');

    % set up the menu items and declare their callbacks
    SCP.handles.file =          uimenu('Label','File');
    SCP.handles.settings =      uimenu('Label','Settings');
    set(SCP.handles.h_fig,'DockControls','off'); %Changed in 1.0.2
    SCP.handles.automate =      uimenu('Label','Automate'); %Added in 1.0.6
    SCP.handles.help =          uimenu('Label','Help'); %Added in 1.0.5

    SILLSNEW = ['delquery = questdlg(''Would you like to save the current project?'',''SILLS Query'',''Yes'',''No'',''Yes'');'...
        'if strcmp(delquery,''Yes'');'...
            'if isempty(A.sillspath);'...
                'A.sillspath = [pwd];'...
            'end;'...
            '[A.sillsfile,A.sillspath] = uiputfile([A.sillspath ''/*.mat''],''Save Project to File'',100,100);'...
            'if A.sillsfile == 0;'...
                'figure(SCP.handles.h_fig);'...
                'return;'...
            'else;'...
                'sillsworkspace = [A.sillspath A.sillsfile];'...
                'save(sillsworkspace);'...
                'for c = 1:50;'...
                    'delete(gcf);'...
                'end;'...
                'clear all;'...
                'SILLS;'...
            'end;'...
        'else;'...
            'for c=1:50;'...
                'delete(gcf);'...
            'end;'...
            'clear all;'...
            'SILLS;'...
        'end;'];    

    SILLSSAVE = ['if isempty(A.sillspath);'...
            'A.sillspath = [pwd];'...
            'end;'...
        '[A.sillsfile,A.sillspath] = uiputfile([A.sillspath ''/*.mat''],''Save Project to File'',100,100);'...
        'if A.sillsfile == 0;'...
            'figure(SCP.handles.h_fig);'...
            'return;'...
        'else;'...
            'sillsworkspace = [A.sillspath A.sillsfile];'...
            'save(sillsworkspace);'...
            'set(SCP.handles.h_fig,''name'',[''SILLS Project: '' A.sillsfile]);'...
            'clear sillsworkspace;'...
        'end;'];
           
    SILLSEXIT = ['delquery = questdlg(''Would you like to save the current project?'',''SILLS Query'',''Yes'',''Exit'',''Yes'');'...
        'if strcmp(delquery,''Yes'');'...
            'if isempty(A.sillspath);'...
                'A.sillspath = [pwd];'...
            'end;'...
            '[A.sillsfile,A.sillspath] = uiputfile([A.sillspath ''/*.mat''],''Save Project to File'',100,100);'...
            'if A.sillsfile == 0;'...
                'figure(SCP.handles.h_fig);'...
                'return;'...
            'else;'...
                'sillsworkspace = [A.sillspath A.sillsfile];'...
                'save(sillsworkspace);'...
                'clear all;'...
                'for c = 1:50;'...
                    'delete(gcf);'...
                'end;'...
            'end;'...    
        'else;'...
            'for c = 1:50;'...
                'delete(gcf);'...
            'end;'...
            'clear all;'...
        'end;'];

    SILLSINPUT = ['A.input_type = get(gcbo,''tag'');'...
                  'if strcmp(A.input_type,''cps'')==1;'...    
                    'if strcmp(get(SCP.handles.cps,''checked''),''off'');'...
                        'set(SCP.handles.cps,''checked'',''on'');'...
                        'set(SCP.handles.counts,''checked'',''off'');'...
                    'end;'...
                  'else;'...
                    'if strcmp(get(SCP.handles.counts,''checked''),''off'');'...
                        'set(SCP.handles.counts,''checked'',''on'');'...
                        'set(SCP.handles.cps,''checked'',''off'');'...
                    'end;'...
                  'end;'];
                 
    SCP.handles.wkspnew = uimenu(SCP.handles.file,'Label','New Project','Callback',SILLSNEW);
    SCP.handles.wkspopen = uimenu(SCP.handles.file,'Label','Open Project','Callback','SILLSOPEN');
    SCP.handles.wkspsave = uimenu(SCP.handles.file,'Label','Save Project','Callback',SILLSSAVE);
    SCP.handles.exitsave = uimenu(SCP.handles.file,'Label','Exit','Callback',SILLSEXIT);
    set(SCP.handles.h_fig,'CloseRequestFcn',SILLSEXIT);
    
    SCP.handles.input =    uimenu(SCP.handles.settings,'Label','Input Format');
    SCP.handles.cps =      uimenu(SCP.handles.input,'Label','Counts per second','tag','cps','checked','on','Callback',SILLSINPUT);
    SCP.handles.counts =   uimenu(SCP.handles.input,'Label','Absolute counts','tag','cts','checked','off','Callback',SILLSINPUT);
   
    SCP.handles.time_format =   uimenu(SCP.handles.settings,'Label','Time Format');
    SCP.handles.drifthhmm =     uimenu(SCP.handles.time_format,'Label','hh:mm','tag','hhmm','checked','on','Callback','DRIFTSETTINGS');
    SCP.handles.driftpoints =   uimenu(SCP.handles.time_format,'Label','Integer time points','tag','integer_points','Callback','DRIFTSETTINGS');
    
    SCP.handles.autotime =      uimenu(SCP.handles.automate,'Label','Retrieve Times from File Info','Callback','AUTOTIME'); %Added in 1.0.5
    SCP.handles.autoint =       uimenu(SCP.handles.automate,'Label','Set Integration Intervals Automatically','Callback','AUTOINT'); %Added in 1.0.6

    SCP.handles.SRM =           uimenu(SCP.handles.settings,'Label','Standard Reference Materials');
    SCP.handles.SRMload =       uimenu(SCP.handles.SRM,'Label','Load SRM from file','Callback','USERSRM_LOAD');
    SCP.handles.SRMdefine =     uimenu(SCP.handles.SRM,'Label','Define new SRM','Callback','ADD_SRM');
    
    SCP.handles.dwelltimes =    uimenu(SCP.handles.settings,'Label','Set Dwell Times','Callback','DWELLTIMES');

    SCP.handles.flicker =       uimenu(SCP.handles.settings,'Label','Set Flicker Noise','Callback','FLICKER_SET');
    
    %Added in 1.0.5
    SCP.handles.manual = uimenu(SCP.handles.help,'Label','SILLS Manual','Callback','open([pwd ''/Extras/SILLS Manual.pdf''])');
    SCP.handles.about =  uimenu(SCP.handles.help,'Label','About SILLS',...
        'Callback','msgbox(textread([pwd ''/Extras/about.txt''],''%s'',''delimiter'',''\n''),''About SILLS'')');
    
    %Added in 1.2.0 by M. Wälle
    %to implement a reparation routine for errors like: "Reference to
    %non-existent field ..."
    SCP.handles.reparation = uimenu(SCP.handles.help,'Label','Reparation','Callback','reparation');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 4.2 Set up the frames

    SCP.handles.h_frame2 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame2',...
        'position',[10*sf(1) 340*sf(2) 170*sf(1) 220*sf(2)],...
        'BackgroundColor',[0.5137 0.6 0.6941],'ForegroundColor',[0.5137 0.6 0.6941]);

    SCP.handles.h_frame3 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame3',...
        'position',[10*sf(1) 10*sf(2) 170*sf(1) 320*sf(2)],...
        'Backgroundcolor',[0.8039 0.7529 0.6902],'Foregroundcolor',[0.8039 0.7529 0.6902]);

    SCP.handles.h_frame4 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame',...
        'position',[185*sf(1) 340*sf(2) 235*sf(1) 220*sf(2)],...
        'Backgroundcolor',[0 0 0],'Foregroundcolor',[0.5137 0.6 0.6941]);

    SCP.handles.h_frame5 =      uipanel(SCP.handles.h_fig,'units','pixels','tag','SCP.handles.h_frame5',...
        'position',[185*sf(1) 10*sf(2) 235*sf(1) 320*sf(2)],...
        'Backgroundcolor',[ 0 0 0],'Foregroundcolor',[0.8039 0.7529 0.6902]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 4.4 set up GUI objects for the standard

    SCP.handles.h_load_std_button =     uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_load_std_button',...
        'Callback','STDFILE_LOAD',...
        'string','Load New Standard','Fontweight','bold',...
        'position',[20*sf(1) 520*sf(2) 150*sf(1) 30*sf(2)],...
        'backgroundcolor',[0.5137 0.6 0.6941]); 
    
    SCP.handles.h_currentSTD_header =       uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_header',...
        'string','Current Standards:','ForegroundColor',[1 1 1],'BackgroundColor',[0.5137 0.6 0.6941],...
        'HorizontalAlignment','left','position',[20*sf(1) 490*sf(2) 150*sf(1) 20*sf(2)]);

    SCP.handles.h_currentSTD_popup =        uicontrol(SCP.handles.h_fig,'style','popupmenu','tag','SCP.handles.h_currentSTD_popup',...
        'string','< load a standard >','Callback','SILLSFIG_UPDATE','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[20*sf(1) 475*sf(2) 150*sf(1) 20*sf(2)]);
    % NB: as new standards are added, 'A.STDPOPUPLIST' is expanded and the popup is updated 
    
    SCP.handles.h_std_plot_button =         uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_std_plot_button',...
        'string','Plot Selected Standard','position',[20*sf(1) 430*sf(2) 150*sf(1) 30*sf(2)],...
        'backgroundcolor',[0.5137 0.6 0.6941],'Callback','STDPLOT'); 

    SCP.handles.h_std_delete_button =       uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_std_delete_button',...
        'string','Delete Selected Standard','Callback','STDDELETE','position',[20*sf(1) 390*sf(2) 150*sf(1) 30*sf(2)],'backgroundcolor',[0.5137 0.6 0.6941]);

  
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 4.5 Set up the text display elements for the current (i.e. selected) standard

    SCP.handles.h_currentSTD_header2 =      uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_header2',...
        'string','Data for Selected Standard','Fontweight','bold','ForegroundColor',[0.5137 0.6 0.6941],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 525*sf(2) 180*sf(1) 20*sf(2)]);

    SCP.handles.h_currentSTD_filename =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_filename',...
        'string','filename:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[200*sf(1) 505*sf(2) 70*sf(1) 20*sf(2)]);

    SCP.handles.h_currentSTD_SRM =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_SRM',...
        'string','Assign SRM:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[200*sf(1) 480*sf(2) 70*sf(1) 20*sf(2)]);

    SCP.handles.h_currentSTD_driftset_header =      uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_driftset_header',...
        'string','Assign time:','position',[200*sf(1) 455*sf(2) 70*sf(1) 20*sf(2)],'HorizontalAlignment','right',...
        'backgroundcolor',[0 0 0],'foregroundcolor',[.8 .8 .8]); 
    
    SCP.handles.h_currentSTD_bg =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bg',...
        'string','BKGND','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 430*sf(2) 80*sf(1) 20*sf(2)]);
    SCP.handles.h_currentSTD_bgfrom =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgfrom',...
        'string','from:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 420*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentSTD_bgto =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgto',...
        'string','to:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 405*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentSTD_bgtotal =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgtotal',...
        'string','total:','HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 390*sf(2) 50*sf(1) 15*sf(2)]);

    SCP.handles.h_currentSTD_sig =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sig',...
        'string','SIGNAL','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[340*sf(1) 430*sf(2) 60*sf(1) 20*sf(2)]);

    SCP.handles.h_currentSTD_filename_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_filename_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','left','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[280*sf(1) 505*sf(2) 120*sf(1) 20*sf(2)]);
    
    SCP.handles.h_currentSTD_SRM_out = uicontrol(SCP.handles.h_fig,'style','popup','tag','SCP.handles.h_currentSTD_SRM_out','string',A.SRMPOPUPLIST,'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','left','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],'Callback','SILLSFIG_UPDATE',...
        'position',[280*sf(1) 485*sf(2) 120*sf(1) 20*sf(2)],'visible','off');
        
    SCP.handles.h_currentSTD_drifthh_edit = uicontrol(SCP.handles.h_fig,'style','edit','tag','SCP.handles.h_currentSTD_drifthh_edit',...
        'HorizontalAlignment','center','ForegroundColor',[0 0 0],'BackgroundColor',[1 1 1],'Callback','TIMESET',...
        'position',[280*sf(1) 460*sf(2) 25*sf(1) 20*sf(2)],'Visible','off');
    SCP.handles.h_currentSTD_driftcolon = uicontrol(SCP.handles.h_fig,'style','text','string',':','tag','SCP.handles.h_currentSTD_driftcolon',...
        'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[307*sf(1) 455*sf(2) 5*sf(1) 20*sf(2)],'Visible','off');
    SCP.handles.h_currentSTD_driftmm_edit = uicontrol(SCP.handles.h_fig,'style','edit','tag','SCP.handles.h_currentSTD_driftmm_edit',...
        'HorizontalAlignment','center','ForegroundColor',[0 0 0],'BackgroundColor',[1 1 1],'Callback','TIMESET',...
        'position',[315*sf(1) 460*sf(2) 25*sf(1) 20*sf(2)],'Visible','off');

    TIMEPT_STDASSIGN = 'STD(A.DC).timepoint = get(gco,''value'');';
                           
    SCP.handles.h_currentSTD_driftpoints_popup = uicontrol(SCP.handles.h_fig,'style','popup','tag','SCP.handles.h_currentSTD_driftpoints_popup',...
        'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],'string',1:A.timepoints,'HorizontalAlignment','right','Callback',TIMEPT_STDASSIGN,...
        'position',[280*sf(1) 460*sf(2) 50*sf(1) 20*sf(2)],'Visible','off');
    
    SCP.handles.h_currentSTD_bgfrom_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgfrom_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 420*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentSTD_bgto_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgto_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 405*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentSTD_bgtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_bgtotal_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 390*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentSTD_sigfrom_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sigfrom_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[340*sf(1) 420*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentSTD_sigto_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sigto_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[340*sf(1) 405*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentSTD_sigtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentSTD_sigtotal_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[340*sf(1) 390*sf(2) 40*sf(1) 15*sf(2)]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 4.6 Set up the GUI elements for the current unknown

    SCP.handles.h_currentUNK_header =       uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_header',...
        'string','Current Unknowns:','ForegroundColor',[1 1 1],'BackgroundColor',[0.8039 0.7529 0.6902],...
        'HorizontalAlignment','left','position',[20*sf(1) 260*sf(2) 150*sf(1) 20*sf(2)]);

    SCP.handles.h_load_unk_button =     uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_load_unk_button',...
        'Callback','UNKFILE_LOAD',...
        'string','Load New Unknown','Fontweight','bold',...
        'position',[20*sf(1) 290*sf(2) 150*sf(1) 30*sf(2)],...
        'backgroundcolor',[0.8039 0.7529 0.6902]); 

    SCP.handles.h_currentUNK_popup =        uicontrol(SCP.handles.h_fig,'style','popupmenu','tag','SCP.handles.h_currentUNK_popup',...
        'string','< load an unknown >','Callback','SILLSFIG_UPDATE','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[20*sf(1) 245*sf(2) 150*sf(1) 20*sf(2)]);
    % NB: as new unknowns are added, 'unkpopuplist' is expanded 

    SCP.handles.h_unk_plot_button =         uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_unk_plot_button',...
        'string','Plot Selected Unknown','position',[20*sf(1) 200*sf(2) 150*sf(1) 30*sf(2)],...
        'backgroundcolor',[0.8039 0.7529 0.6902],'Callback','UNKPLOT'); 

    SCP.handles.h_unk_copy_button =       uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_unk_copy_button',...
        'string','Copy Selected Unknown','Callback','UNKCOPY','position',[20*sf(1) 160*sf(2) 150*sf(1) 30*sf(2)],'backgroundcolor',[0.8039 0.7529 0.6902]);

    SCP.handles.h_unk_delete_button =       uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_unk_delete_button',...
        'string','Delete Selected Unknown','Callback','UNKDELETE','position',[20*sf(1) 120*sf(2) 150*sf(1) 30*sf(2)],'backgroundcolor',[0.8039 0.7529 0.6902]);
        
    SCP.handles.h_CALC_manager = uicontrol(SCP.handles.h_fig,'style','pushbutton','tag','SCP.handles.h_CALC_manager',...
        'string','CALCULATION SETTINGS','Callback','CALC_MANAGER','BackgroundColor',[0.8039 0.7529 0.6902],'position',[20*sf(1) 50*sf(2) 150*sf(1) 60*sf(2)]);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% 4.7 Set up the text display elements for the current (i.e. selected)
% unknown

    SCP.handles.h_currentUNK_header2 =      uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_header2',...
        'string','Data for Selected Unknown','Fontweight','bold','ForegroundColor',[0.8039 0.7529 0.6902],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 300*sf(2) 180*sf(1) 20*sf(2)]);

    SCP.handles.h_currentUNK_filename =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_filename',...
        'string','filename:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[200*sf(1) 280*sf(2) 70*sf(1) 20*sf(2)]);

    SCP.handles.h_currentUNK_bg =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bg',...
        'string','BKGND','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 210*sf(2) 80*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_bgfrom =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgfrom',...
        'string','from:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 180*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_bgto =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgto',...
        'string','to:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 165*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_subtotal =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_total',...
        'string','subtotal:','HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 150*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_total =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_total',...
        'string','total:','HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 135*sf(2) 50*sf(1) 15*sf(2)]);
    
    SCP.handles.h_currentUNK_mat =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat',...
        'string','MATRIX','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[340*sf(1) 210*sf(2) 60*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_mat1 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat1',...
        'string','Comp. 1','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[315*sf(1) 195*sf(2) 50*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_mat2 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat1',...
        'string','Comp. 2','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[365*sf(1) 195*sf(2) 50*sf(1) 20*sf(2)]);
    
    SCP.handles.h_currentUNK_filename_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_filename_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','left','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[280*sf(1) 280*sf(2) 120*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_bgfrom_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgfrom_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 180*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_bgto_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgto_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 165*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_bgtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_bgtotal_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[260*sf(1) 135*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_mat1from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_matfrom_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
        'position',[315*sf(1) 180*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_mat1to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_matto_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
        'position',[315*sf(1) 165*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_mat2from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat2from_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
        'position',[365*sf(1) 180*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_mat2to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat2to_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 1 .8],'BackgroundColor',[0 0 0],...
        'position',[365*sf(1) 165*sf(2) 40*sf(1) 15*sf(2)]);

    SCP.handles.h_currentUNK_mat1total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat1total_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[315*sf(1) 150*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_mat2total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mat2total_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[365*sf(1) 150*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_mattotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_mattotal_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[340*sf(1) 135*sf(2) 40*sf(1) 15*sf(2)]);
        
    SCP.handles.h_currentUNK_sig =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_sig',...
        'string','SIGNAL','HorizontalAlignment','center','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[250*sf(1) 100*sf(2) 150*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_comp1 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1',...
        'string','Comp.1','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[250*sf(1) 85*sf(2) 50*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_comp2 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2',...
        'string','Comp.2','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[300*sf(1) 85*sf(2) 50*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_comp3 =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3',...
        'string','Comp.3','HorizontalAlignment','left','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[350*sf(1) 85*sf(2) 50*sf(1) 20*sf(2)]);
    SCP.handles.h_currentUNK_comp1from =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1from',...
        'string','from:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 70*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp1to =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1to',...
        'string','to:','HorizontalAlignment','right','ForegroundColor',[.8 .8 .8],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 55*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp1total =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1total',...
        'string','subtotal:','HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 40*sf(2) 50*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_sigtotal =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_sigtotal',...
        'string','total:','HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[190*sf(1) 25*sf(2) 50*sf(1) 15*sf(2)]);
    

    SCP.handles.h_currentUNK_comp1from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1from_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[250*sf(1) 70*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp1to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1to_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[250*sf(1) 55*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp1total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp1total_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[250*sf(1) 40*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp2from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2from_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[300*sf(1) 70*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp2to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2to_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[300*sf(1) 55*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp2total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp2total_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[300*sf(1) 40*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp3from_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3from_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[350*sf(1) 70*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp3to_out = uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3to_out','string',[],'ForegroundColor',[1 1 1],...
        'HorizontalAlignment','right','ForegroundColor',[.8 .8 1],'BackgroundColor',[0 0 0],...
        'position',[350*sf(1) 55*sf(2) 40*sf(1) 15*sf(2)]);
    SCP.handles.h_currentUNK_comp3total_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_comp3total_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
        'position',[350*sf(1) 40*sf(2) 40*sf(1) 15*sf(2)]);
 
    SCP.handles.h_currentUNK_sigtotal_out =     uicontrol(SCP.handles.h_fig,'style','text','tag','SCP.handles.h_currentUNK_sigtotal_out',...
        'string',[],'HorizontalAlignment','right','ForegroundColor','y','BackgroundColor',[0 0 0],...
        'position',[300*sf(1) 25*sf(2) 40*sf(1) 15*sf(2)]);

%%%%%% Section 5 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Display the logo

logo = imread([pwd '/Extras/SILLSlogo.jpg']); %Changed in 1.0.4
image(logo);
set(gca,'visible','off','units','pixels','position',[50*sf(1) 570*sf(2) 320*sf(1) 184*sf(2)]);
clear logo

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%% Section 6 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% reduce the fontsize if a lower resolution monitor is being used

if sf(1) < 0.8
    child = get(gcf,'children');
    notmenu = find(strcmp(get(child,'type'),'uimenu') == 0);
    child = child(notmenu);
    set(child,'fontsize',7);
    clear child notmenu
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

