%UNKPLOT

if A.UNK_num == 0
    return
end

A.K = A.K + 1;

currentfig = get(gcf,'tag');

if strcmp(currentfig,'SILLS Control Panel') == 1
    A.KC = get(SCP.handles.h_currentUNK_popup,'Value');
elseif strcmp(currentfig,'SILLS Calculation Manager') == 1;
    A.KC = get(gco,'Userdata');
end
clear currentfig     

if strcmp(UNK(A.KC).figure_state,'open') % if the figure is already open

    figure(UNK(A.KC).handles.h_unkfig);  % get the figure

else
    
%%%%%%%%% Replace all 0 values by a very low dummy value %%%%%% 
%%%%%%%%% Added in 1.0.2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

for a = 2:size(UNK(A.KC).data,2) %cycle through elements
    for b = 1:size(UNK(A.KC).data,1) %cycle through timesteps
        if UNK(A.KC).data(b,a) == 0
           UNK(A.KC).data(b,a) = A.dummy;
        end
    end
end
clear a b


UNK(A.KC).handles.h_unkfig = figure('name',['Unknown (' UNK(A.KC).fileinfo.name ')'],...
    'units','pixels','tag',UNK(A.KC).fileinfo.name,'NumberTitle','off','menubar','none','WindowButtonDownFcn','UNKPICKER',...
    'position',[10*sf(1) 100*sf(2) 770*sf(1) 850*sf(2)],'Color',[0.8039 0.7529 0.6902],'UserData',UNK(A.KC).order_opened);

set(UNK(A.KC).handles.h_unkfig,'CloseRequestFcn','UNKDELETE');

%%%%%%%%% Show the file menu to save and print %%%%%%%%%%%%%%%% 
%%%%%%%%% Added in 1.0.2 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
UNK(A.KC).handles.h_figuremenu = uimenu('Label','File');
uimenu(UNK(A.KC).handles.h_figuremenu,'Label','Save As...','Callback','SAVEFIGAS');
uimenu(UNK(A.KC).handles.h_figuremenu,'Label','Page Setup...','Callback','pagesetupdlg(gcf)','Separator','on');
uimenu(UNK(A.KC).handles.h_figuremenu,'Label','Print Preview...','Callback','printpreview(gcf)');
uimenu(UNK(A.KC).handles.h_figuremenu,'Label','Print...','Callback','printdlg(gcf)');
set(UNK(A.KC).handles.h_unkfig,'DockControls','off','PaperPositionMode','auto');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%%%%%%%%% Show the display mode menu %%%%%%%%%%%%%%%%%%%%%%%%%% 
%%%%%%%%% Added in 1.0.3 %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
UNK(A.KC).handles.h_modemenu = uimenu('Label','Switch Display Mode');
UNK(A.KC).handles.h_elementmenu = uimenu(UNK(A.KC).handles.h_modemenu,'Label','Plot Isotopes','Enable','off','Callback','mode=''element'';UNKRATIO');
UNK(A.KC).handles.h_ratiomenu = uimenu(UNK(A.KC).handles.h_modemenu,'Label','Plot Ratios','Callback','mode=''ratio'';UNKRATIO');
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
        
UNK(A.KC).handles.h_unk_resetx_button = uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton',...
    'string','Reset Axes','Callback',UNKRESETX,...
    'backgroundcolor',[0.8039 0.7529 0.6902],'ForegroundColor',[0 0 0],...
    'Position',[630*sf(1) 10*sf(2) 130*sf(1) 30*sf(2)]);

UNK(A.KC).handles.h_toggle_all = uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton',...
    'string','Show All','Callback','UNKLINE',...
    'backgroundcolor',[0.8039 0.7529 0.6902],'ForegroundColor',[0 0 0],...
    'Position',[630*sf(1) 75*sf(2) 65*sf(1) 30*sf(2)]);

UNK(A.KC).handles.h_toggle_none = uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton',...
    'string','Show None','Callback','UNKLINE',...
    'backgroundcolor',[0.8039 0.7529 0.6902],'ForegroundColor',[0 0 0],...
    'Position',[695*sf(1) 75*sf(2) 65*sf(1) 30*sf(2)]);

UNK(A.KC).handles.h_spikebutton = uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton',...
    'String','Spike Elimination','FontWeight','bold','Callback','spike',...
    'backgroundcolor',[0.8039 0.7529 0.6902],'ForegroundColor',[0 0 0],...
    'Position',[630*sf(1) 110*sf(2) 130*sf(1) 30*sf(2)],...
    'tag','unknown'); %Added in 1.1.1
if strcmp(UNK(A.KC).spikestatus,'finished') == 1
    set(UNK(A.KC).handles.h_spikebutton,'FontWeight','normal','String','Spike Elimination (done)');
end
    
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%set up the mutually exclusive 'background' and 'signal' radio buttons

UNK(A.KC).handles.radiogroup = uibuttongroup('units','pixels','position',[20*sf(1) 10*sf(2) 600*sf(1) 130*sf(2)],'BackgroundColor',[0 0 0]);

UNK(A.KC).handles.radio_unk1 = uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio',...
    'string','ZOOM','Fontweight','bold','units','pixels',...
    'Position',[620*sf(1) 35*sf(2) 60*sf(1) 15*sf(2)],'ForegroundColor',[1 1 1],'BackgroundColor',[0.8039 0.7529 0.6902],...
    'Parent',UNK(A.KC).handles.radiogroup);

UNK(A.KC).handles.radio_unk2 = uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio',...
    'string','BKGND','Fontweight','bold','units','pixels','Value',1,...
    'Position',[90*sf(1) 90*sf(2) 60*sf(1) 15*sf(2)],'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'Parent',UNK(A.KC).handles.radiogroup);

UNK(A.KC).handles.radio_unk3 = uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio',...
     'string','Comp. 1','units','pixels',...
     'Position',[410*sf(1) 90*sf(2) 60*sf(1) 15*sf(2)],'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
     'Parent',UNK(A.KC).handles.radiogroup);
 
UNK(A.KC).handles.radio_unk4 = uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio',...
    'string','Comp. 2','units','pixels',...
    'Position',[480*sf(1) 90*sf(2) 60*sf(1) 15*sf(2)],'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'Parent',UNK(A.KC).handles.radiogroup);

UNK(A.KC).handles.radio_unk5 = uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio',...
    'string','Comp. 1','units','pixels',...
    'Position',[180*sf(1) 90*sf(2) 60*sf(1) 15*sf(2)],'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'Parent',UNK(A.KC).handles.radiogroup);

UNK(A.KC).handles.radio_unk6 = uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio',...
    'string','Comp. 2','units','pixels',...
    'Position',[250*sf(1) 90*sf(2) 60*sf(1) 15*sf(2)],'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'Parent',UNK(A.KC).handles.radiogroup);

UNK(A.KC).handles.radio_unk7 = uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio',...
    'string','Comp. 3','units','pixels',...
    'Position',[320*sf(1) 90*sf(2) 60*sf(1) 15*sf(2)],'ForegroundColor',[1 1 1],'BackgroundColor',[0 0 0],...
    'Parent',UNK(A.KC).handles.radiogroup);


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% when this box is clicked the user can input a lower time bracket for
% the background portion of the standard file. The callback UNKBG_USERFROM.m
% includes a routine to determine the time value that most closely matches this input.

UNK(A.KC).handles.h_unk_from_text =          uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unk_from_text',...
    'string','from:','HorizontalAlignment','right',...
    'ForegroundColor',[.9 .9 .9],...
    'position',[50*sf(1) 75*sf(2) 50*sf(1) 20*sf(2)],...
    'backgroundcolor',[0 0 0]);
UNK(A.KC).handles.h_unk_to_text =            uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unk_to_text',...
    'string','to:','HorizontalAlignment','right',...
    'ForegroundColor',[.9 .9 .9],...
    'position',[50*sf(1) 55*sf(2) 50*sf(1) 20*sf(2)],...
    'backgroundcolor',[0 0 0]);
UNK(A.KC).handles.h_unk_total_text =            uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unk_to_text',...
    'string','total:','HorizontalAlignment','right',...
    'ForegroundColor','y',...
    'position',[50*sf(1) 35*sf(2) 50*sf(1) 20*sf(2)],...
    'backgroundcolor',[0 0 0]);

UNK(A.KC).handles.h_unkbg_userfrom =         uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkbg_userfrom',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['bgfrom' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.9 .9 .9],...
    'position',[110*sf(1) 80*sf(2) 60*sf(1) 15*sf(2)]); %the -1000 factor is so make the number-to-string conversion possible (order_opened is negative)
UNK(A.KC).handles.h_unkbg_userto =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkbg_userto',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['bgto' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.9 .9 .9],...
    'position',[110*sf(1) 60*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkbg_total =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unkbg_total',...
    'HorizontalAlignment','right','BackgroundColor',[0 0 0],'ForegroundColor','y',...
    'position',[105*sf(1) 40*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkbg_erase =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton','tag','UNK.handles.h_unkbg_erase',...
    'HorizontalAlignment','center','string','ERASE','Callback','ERASE_UNKWINDOW','position',[110*sf(1) 20*sf(2) 60*sf(1) 15*sf(2)]);

UNK(A.KC).handles.h_unkmat_text =        uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unkmat_text',...
    'String','MATRIX','Fontweight','bold','BackgroundColor',[0 0 0],'ForegroundColor',[1 1 1],'HorizontalAlignment','center',...
    'position',[430*sf(1) 115*sf(2) 130*sf(1) 15*sf(2)]);

UNK(A.KC).handles.h_unkmat1_userfrom =        uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkmat1_userfrom',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['mat1from' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.9 1 .9],...
    'position',[430*sf(1) 80*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkmat1_userto =          uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkmat_userto',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['mat1to' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.9 1 .9],...
    'position',[430*sf(1) 60*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkmat1_total =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unkmat1_total',...
    'HorizontalAlignment','right','BackgroundColor',[0 0 0],'ForegroundColor','w',...
    'position',[425*sf(1) 40*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkmat1_erase =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton','tag','UNK.handles.h_unkmat1_erase',...
    'HorizontalAlignment','center','string','ERASE','Callback','ERASE_UNKWINDOW','position',[430*sf(1) 20*sf(2) 60*sf(1) 15*sf(2)]);

UNK(A.KC).handles.h_unkmat2_userfrom =        uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkmat2_userfrom',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['mat2from' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.8 1 .8],...
    'position',[500*sf(1) 80*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkmat2_userto =          uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkmat2_userto',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['mat2to' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.8 1 .8],...
    'position',[500*sf(1) 60*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkmat2_total =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unkmat2_total',...
    'HorizontalAlignment','right','BackgroundColor',[0 0 0],'ForegroundColor','w',...
    'position',[495*sf(1) 40*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkmat2_erase =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton','tag','UNK.handles.h_unkmat2_erase',...
    'HorizontalAlignment','center','string','ERASE','Callback','ERASE_UNKWINDOW','position',[500*sf(1) 20*sf(2) 60*sf(1) 15*sf(2)]);

UNK(A.KC).handles.h_unksig_text =        uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unksig_text',...
    'String','SIGNAL','Fontweight','bold','BackgroundColor',[0 0 0],'ForegroundColor',[1 1 1],'HorizontalAlignment','center',...
    'position',[200*sf(1) 115*sf(2) 200*sf(1) 15*sf(2)]);

UNK(A.KC).handles.h_unkcomp1_userfrom =        uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkcomp1_userfrom',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['comp1from' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.9 .9 1],...
    'position',[200*sf(1) 80*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp1_userto =          uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkcomp1_userto',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['comp1to' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.9 .9 1],...
    'position',[200*sf(1) 60*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp1_total =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unkcomp1_total',...
    'HorizontalAlignment','right','BackgroundColor',[0 0 0],'ForegroundColor','w',...
    'position',[195*sf(1) 40*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp1_erase =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton','tag','UNK.handles.h_unkcomp1_erase',...
    'HorizontalAlignment','center','string','ERASE','Callback','ERASE_UNKWINDOW','position',[200*sf(1) 20*sf(2) 60*sf(1) 15*sf(2)]);

UNK(A.KC).handles.h_unkcomp2_userfrom =        uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkcomp2_userfrom',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['comp2from' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.8 .8 1],...
    'position',[270*sf(1) 80*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp2_userto =          uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkcomp2_userto',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['comp2to' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.8 .8 1],...
    'position',[270*sf(1) 60*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp2_total =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unkcomp2_total',...
    'HorizontalAlignment','right','BackgroundColor',[0 0 0],'ForegroundColor','w',...
    'position',[265*sf(1) 40*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp2_erase =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton','tag','UNK.handles.h_unkcomp2_erase',...
    'HorizontalAlignment','center','string','ERASE','Callback','ERASE_UNKWINDOW','position',[270*sf(1) 20*sf(2) 60*sf(1) 15*sf(2)]);

UNK(A.KC).handles.h_unkcomp3_userfrom =        uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkcomp3_userfrom',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['comp3from' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.7 .7 1],...
    'position',[340*sf(1) 80*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp3_userto =          uicontrol(UNK(A.KC).handles.h_unkfig,'style','edit','tag','UNK.handles.h_unkcomp3_userto',...
    'Callback','UNK_MANUAL_ADJUST','UserData',['comp3to' -1000*UNK(A.KC).order_opened],...
    'HorizontalAlignment','right','BackgroundColor',[.7 .7 1],...
    'position',[340*sf(1) 60*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp3_total =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','text','tag','UNK.handles.h_unkcomp3_total',...
    'HorizontalAlignment','right','BackgroundColor',[0 0 0],'ForegroundColor','w',...
    'position',[335*sf(1) 40*sf(2) 60*sf(1) 15*sf(2)]);
UNK(A.KC).handles.h_unkcomp3_erase =           uicontrol(UNK(A.KC).handles.h_unkfig,'style','pushbutton','tag','UNK.handles.h_unkcomp3_erase',...
    'HorizontalAlignment','center','string','ERASE','Callback','ERASE_UNKWINDOW','position',[340*sf(1) 20*sf(2) 60*sf(1) 15*sf(2)]);


%write an array of values for plotting a legend
UNK(A.KC).legendarray(1,1) = 3;
UNK(A.KC).legendarray(2,1) = 6;

C = UNK(A.UNK_num).num_elements;

for c = 1:C; %for each element
    UNK(A.KC).legendarray(:,c+1) = C + 1 - c; 
    UNK(A.KC).legendentry_positions(1,c) = 7;
    UNK(A.KC).legendentry_positions(2,c) = C + 1 - c;
end

UNK(A.KC).legendentries = UNK(A.UNK_num).colheaders(2:end);
UNK(A.KC).legendentry_positions = UNK(A.KC).legendentry_positions;

%plot the legend
UNK(A.KC).handles.h_unklegend = subplot(1,2,2);plot(UNK(A.KC).legendarray(:,1),UNK(A.KC).legendarray(:,2:end),'tag','element'); %Modified in 1.0.3
set(UNK(A.KC).handles.h_unklegend,'units','pixels','XLim',[0 10],'YLim',[0 UNK(A.UNK_num).num_elements+1],...
    'position',[630*sf(1) 160*sf(2) 130*sf(1) 660*sf(2)],'Nextplot','add',... %Modified in 1.0.3;
    'XTick',[],'XTickLabel',[],'YTick',[],'YTickLabel',[],'tag','UNK.handles.h_unklegend'); %Added tag in 1.0.5

UNK(A.KC).legendtext = text(UNK(A.KC).legendentry_positions(1,:),UNK(A.KC).legendentry_positions(2,:),UNK(A.KC).legendentries);
set(UNK(A.KC).legendtext,'FontSize',8,'tag','element'); %Modified in 1.0.3

%determine the pixel position of each text item.
UNK(A.KC).incrmt = 660/(C+1);

for c = 1:C
    UNK(A.KC).handles.h_unkline_toggle(c) =   uicontrol(UNK(A.KC).handles.h_unkfig,'style','radio','position',[640*sf(1) (812-c*UNK(A.KC).incrmt)*sf(2) 15*sf(1) 15*sf(2)],...
    'BackgroundColor',[1 1 1],'Value',1,'Userdata',c,'Callback','UNKLINE');
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%plot the data

UNK(A.KC).handles.h_unkplot= subplot(1,2,1);plot(UNK(A.KC).data(:,1),UNK(A.KC).data(:,2:end));

%.....................................................
%attach userdata to each plotted line.
UNK(A.KC).lines = get(UNK(A.KC).handles.h_unkplot,'Children');

for c = 1:C
    set(UNK(A.KC).lines(c),'userdata',C+1-c);
    set(UNK(A.KC).lines(c),'tag','element'); %Added in 1.0.3
end
clear c C
%.....................................................

%set the title
%A.KC = get(SCP.handles.h_currentUNK_popup,'value');
figtit = A.UNKPOPUPLIST(A.KC);
title(figtit);
clear figtit;

set(UNK(A.KC).handles.h_unkplot,'Fontsize',8,'units','pixels','position',[40*sf(1) 160*sf(2) 580*sf(1) 660*sf(2)],'Yscale','log');
ylimold = get(UNK(A.KC).handles.h_unkplot,'YLim'); %this and next 3 lines added in 1.0.2
ylimold(1) = 10;
set(UNK(A.KC).handles.h_unkplot,'YLim',ylimold);
clear ylimold
set(UNK(A.KC).handles.h_unkplot,'tag','UNK.handles.h_unkplot'); %Added in 1.0.5
UNK(A.KC).XLim_orig = get(UNK(A.KC).handles.h_unkplot,'XLim');
UNK(A.KC).YLim_orig = get(UNK(A.KC).handles.h_unkplot,'YLim');


    % declare UNK(A.KC).handles.h_unkfig open
    UNK(A.KC).figure_state = 'open';
    A.UNKfigs_open = {UNK.figure_state};
    A.UNKfigs_open = strcmp(A.UNKfigs_open,'open');

    %add the patches

    if ~isempty(UNK(A.KC).bgwindow)
        UNK(A.KC).handles.h_bgpatch = patch('faces',[1 2 3 4],...
            'vertices',[UNK(A.KC).bgwindow(1) UNK(A.KC).YLim_orig(1);UNK(A.KC).bgwindow(2) UNK(A.KC).YLim_orig(1);UNK(A.KC).bgwindow(2) UNK(A.KC).YLim_orig(2);UNK(A.KC).bgwindow(1) UNK(A.KC).YLim_orig(2)],...
            'EdgeColor','none','facecolor',[.9 .9 .9],'FaceAlpha',0.2);
        set(UNK(A.KC).handles.h_unkbg_userfrom,'string',UNK(A.KC).bgwindow(1,1),'Value',UNK(A.KC).bgwindow(1,1));
        set(UNK(A.KC).handles.h_unkbg_userto,'string',UNK(A.KC).bgwindow(1,2),'Value',UNK(A.KC).bgwindow(1,2));
    end

    if ~isempty(UNK(A.KC).mat1window)
        UNK(A.KC).handles.h_mat1patch = patch('faces',[1 2 3 4],...
            'vertices',[UNK(A.KC).mat1window(1) UNK(A.KC).YLim_orig(1);UNK(A.KC).mat1window(2) UNK(A.KC).YLim_orig(1);UNK(A.KC).mat1window(2) UNK(A.KC).YLim_orig(2);UNK(A.KC).mat1window(1) UNK(A.KC).YLim_orig(2)],...
            'EdgeColor','none','facecolor',[.9 1 .9],'FaceAlpha',0.2);
        set(UNK(A.KC).handles.h_unkmat1_userfrom,'string',UNK(A.KC).mat1window(1,1),'Value',UNK(A.KC).mat1window(1,1));
        set(UNK(A.KC).handles.h_unkmat1_userto,'string',UNK(A.KC).mat1window(1,2),'Value',UNK(A.KC).mat1window(1,2));
    end

    if ~isempty(UNK(A.KC).mat2window)
        UNK(A.KC).handles.h_mat2patch = patch('faces',[1 2 3 4],...
            'vertices',[UNK(A.KC).mat2window(1) UNK(A.KC).YLim_orig(1);UNK(A.KC).mat2window(2) UNK(A.KC).YLim_orig(1);UNK(A.KC).mat2window(2) UNK(A.KC).YLim_orig(2);UNK(A.KC).mat2window(1) UNK(A.KC).YLim_orig(2)],...
            'EdgeColor','none','facecolor',[.8 1 .8],'FaceAlpha',0.2);
        set(UNK(A.KC).handles.h_unkmat2_userfrom,'string',UNK(A.KC).mat2window(1,1),'Value',UNK(A.KC).mat2window(1,1));
        set(UNK(A.KC).handles.h_unkmat2_userto,'string',UNK(A.KC).mat2window(1,2),'Value',UNK(A.KC).mat2window(1,2));
    end
    
    if ~isempty(UNK(A.KC).comp1window)
        UNK(A.KC).handles.h_comp1patch = patch('faces',[1 2 3 4],...
            'vertices',[UNK(A.KC).comp1window(1) UNK(A.KC).YLim_orig(1);UNK(A.KC).comp1window(2) UNK(A.KC).YLim_orig(1);UNK(A.KC).comp1window(2) UNK(A.KC).YLim_orig(2);UNK(A.KC).comp1window(1) UNK(A.KC).YLim_orig(2)],...
            'EdgeColor','none','facecolor',[.9 .9 1],'FaceAlpha',0.2);
        set(UNK(A.KC).handles.h_unkcomp1_userfrom,'string',UNK(A.KC).comp1window(1,1),'Value',UNK(A.KC).comp1window(1,1));
        set(UNK(A.KC).handles.h_unkcomp1_userto,'string',UNK(A.KC).comp1window(1,2),'Value',UNK(A.KC).comp1window(1,2));
    end

    if ~isempty(UNK(A.KC).comp2window)
        UNK(A.KC).handles.h_comp2patch = patch('faces',[1 2 3 4],...
            'vertices',[UNK(A.KC).comp2window(1) UNK(A.KC).YLim_orig(1);UNK(A.KC).comp2window(2) UNK(A.KC).YLim_orig(1);UNK(A.KC).comp2window(2) UNK(A.KC).YLim_orig(2);UNK(A.KC).comp2window(1) UNK(A.KC).YLim_orig(2)],...
            'EdgeColor','none','facecolor',[.8 .8 1],'FaceAlpha',0.2);
        set(UNK(A.KC).handles.h_unkcomp2_userfrom,'string',UNK(A.KC).comp2window(1,1),'Value',UNK(A.KC).comp2window(1,1));
        set(UNK(A.KC).handles.h_unkcomp2_userto,'string',UNK(A.KC).comp2window(1,2),'Value',UNK(A.KC).comp2window(1,2));
    end

    if ~isempty(UNK(A.KC).comp3window)
        UNK(A.KC).handles.h_comp3patch = patch('faces',[1 2 3 4],...
            'vertices',[UNK(A.KC).comp3window(1) UNK(A.KC).YLim_orig(1);UNK(A.KC).comp3window(2) UNK(A.KC).YLim_orig(1);UNK(A.KC).comp3window(2) UNK(A.KC).YLim_orig(2);UNK(A.KC).comp3window(1) UNK(A.KC).YLim_orig(2)],...
            'EdgeColor','none','facecolor',[.7 .7 1],'FaceAlpha',0.2);
        set(UNK(A.KC).handles.h_unkcomp3_userfrom,'string',UNK(A.KC).comp3window(1,1),'Value',UNK(A.KC).comp3window(1,1));
        set(UNK(A.KC).handles.h_unkcomp3_userto,'string',UNK(A.KC).comp3window(1,2),'Value',UNK(A.KC).comp3window(1,2));
    end


    hold on

    % reduce the fontsize if a lower resolution monitor is being used
    if sf(1) < 0.8
        child = get(gcf,'children');
        notmenu = find(strcmp(get(child,'type'),'uimenu') == 0);
        child = child(notmenu);
        set(child,'fontsize',7);
        set(UNK(A.KC).legendtext,'fontsize',7);
        set(UNK(A.KC).handles.radio_unk1,'fontsize',7);
        set(UNK(A.KC).handles.radio_unk2,'fontsize',7);
        set(UNK(A.KC).handles.radio_unk3,'fontsize',7);
        set(UNK(A.KC).handles.radio_unk4,'fontsize',7);
        set(UNK(A.KC).handles.radio_unk5,'fontsize',7);
        set(UNK(A.KC).handles.radio_unk6,'fontsize',7);
        set(UNK(A.KC).handles.radio_unk7,'fontsize',7);
        clear child notmenu
    end

    SILLSFIG_UPDATE
    figure(UNK(A.KC).handles.h_unkfig)
end